spring.application.name=driver-service
server.port=8082

# MongoDB Configuration (MongoDB Atlas Online Cluster)
spring.data.mongodb.uri=${MONGO_URI:mongodb+srv://ridelink-account:ride12345@ridelinkcluster.x68x1q1.mongodb.net/ridelink_drivers?retryWrites=true&w=majority&appName=RideLinkCluster}

spring.data.mongodb.auto-index-creation=true

jwt.secret=${JWT_SECRET:RideLinkSecretKeyForJWTTokenGenerationMustBeLongEnough256Bits!!}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.driver_service=INFO

