spring.application.name=driver-service
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_drivers
spring.data.mongodb.auto-index-creation=true

jwt.secret=RideLinkSecretKeyForJWTTokenGenerationMustBeLongEnough256Bits!!

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

logging.level.com.driver_service=INFO
